/* 项目插件 */
buildscript {
    ext {
        springVersion = '4.1.1'
        jarVersion = '411'
        /* ['actuator', 'rabbitmq', 'jackson', 'mybatis-druid-mysql', 'spring-cloud', 'redis-lettuce'] */
        dependencieContains = ['actuator', 'jackson', 'mybatis-druid-mysql', 'redis-lettuce']
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springVersion}")
    }
}

/* 项目插件 */
plugins {
    id 'java'
    id 'idea'
    id 'org.springframework.boot' version "${springVersion}"
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.ben-manes.versions' version '0.64.0'
}

apply from: "./gradle9.80-string-boot.${jarVersion}.01.assistant.gradle"

wrapper {
    gradleVersion = '9.8.0'
}

/* 项目信息 */
group 'com.dawn'
version "2026.10.01.${jarVersion}-SNAPSHOT"
description "springboot4-应用助手|jdk27"

/**
 * 包引入
 * implementation 编译的依赖，其他项目无法访问到
 * apk = gradle2.x.compile 生成apk时参与打包。编译时不参与
 * provided = compileOnly 编译时有效不参与打包
 * releaseCompile 仅仅针对release 模式的编译及最终release apk时有效
 * annotationProcessor 注解处理
 **/
dependencies {
    /* ---------------- RELEASE / SNAPSHOT ---------------------- */
    /* implementation "com.dawn:dawn-assistant:2025.09.01.355-RELEASE" */
    implementation files(
        /* "D:\\dev\\snapshot\\dawn-assistant\\build\\libs\\dawn-assistant-2025.09.01.355-SNAPSHOT.jar" */
    )
}

/* ------------------------------------------------------------------------------- */
/* 依赖 */
tasks.register('copyResources', Copy) {
    doFirst {
        logger.lifecycle("-+-- 加载静态 / 配置文件 src/main/resources ---> classes/java/main/resources --+-")
    }
    into(layout.buildDirectory.dir('classes'))
    into("java/main") {
        from("src/main/resources/application-datasources.yml")
        from("src/main/resources/application-plugin.yml")
        from("src/main/resources/application-rabbitmq.yml")
        from("src/main/resources/application-redis.yml")
        from("src/main/resources/application-redises.yml")
        from("src/main/resources/banner.txt")
        from("src/main/resources/logback-spring.xml")
    }
    into("java/main/static") {
        from("src/main/resources/static/index.html")
        /* include('**//*.txt', '**//*.html') */
        /* filter(rootProject.propertiesFilter, org.apache.tools.ant.filters.ReplaceTokens) */
    }
}

tasks.register('javaJar', Jar) {
    doFirst {
        logger.lifecycle("-+-- 构建工具包 --+-")
    }
    /* 指定生成的 jar 包名字 */
    /* [baseName "dawn-assistant"] */
    dependsOn copyResources
    from compileJava
    excludes = [
        "**/DawnAssistantApplication.class",
        "**/generated/",
        "**/previous-compilation-data.bin"
    ]
}

tasks.register('buildJar') {
    doFirst {
        logger.lifecycle('-+-- 开始进行工具包构建, asciidoctor --+-')
    }
    dependsOn javadocJar, sourcesJar, javaJar
    doLast {
        logger.lifecycle('-+-- 构建完成 /build/libs/ --+-')
    }
}

/* ------------------------------------------------------------------------------- */
